server:
  port: 8081
spring:
  main:
    allow-circular-references: true

  application:
    name: lesson43
  datasource:
    url: jdbc:mysql://localhost:3307/cities #?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: Pa$$w0rd
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        default_schema: db
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  liquibase:
    change-log: 'classpath:db/migrations/changeLog.xml'
  data:
    rest:
      base-path: api
management:
  endpoints:
    web:
      exposure:
        include: "*"
  #        include: "health, info, metric, prometheus"
  endpoint:
    health:
      show-details: always
  info:
    # Включает информацию о сборке (spring-boot-maven-plugin)
    build:
      enabled: true
    # Включает информацию о приложении из application.yml
    env:
      enabled: true
    # Включает информацию о git (git-commit-id-plugin)
    git:
      mode: "full"

# Собственно, сама информация
info:
  app:
    # Пример фильтрации свойств Maven
    version: @project.version@
    author: vivanov
    description: This is an example description
