spring:
  main:
    banner-mode: 'off'
  application:
    name: cities
  messages:
    basename: i18n.messages
  data:
    mongodb:
      uri: mongodb://localhost:27017/cities
      database: cities
application:
  nosql:
    type: mongo

mongock:
  runner-type: "ApplicationRunner"
#  change-logs-scan-package:
#    - lesson40.migration
